<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="CpaySWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/CpaySWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/CpaySWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://inm381/Coursework">
    <import location="CpayS.wsdl" namespace="http://inm381/Coursework"/>
    <plnk:partnerLinkType name="CpaySLinkType">
        <plnk:role name="CpaySRole" portType="ns:CpaySPortType"/>
    </plnk:partnerLinkType>
</definitions>
